[2025-06-16T11:27:14.055+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T11:24:45.686238+00:00 [queued]>
[2025-06-16T11:27:15.562+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T11:24:45.686238+00:00 [queued]>
[2025-06-16T11:27:15.578+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-16T11:27:16.002+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-16 11:24:45.686238+00:00
[2025-06-16T11:27:16.134+0000] {standard_task_runner.py:57} INFO - Started process 181 to run task
[2025-06-16T11:27:16.237+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-16T11:24:45.686238+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpt55jay2w']
[2025-06-16T11:27:16.289+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask stream_data_from_api
[2025-06-16T11:28:12.335+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T11:24:45.686238+00:00 [running]> on host 4cbeca56a1a7
[2025-06-16T11:28:18.739+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T11:24:45.686238+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T11:24:45.686238+00:00'
[2025-06-16T11:28:20.677+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.14', 29092)]>: connecting to broker:29092 [('10.89.0.14', 29092) IPv4]
[2025-06-16T11:28:22.683+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 44, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms = 5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-06-16T11:28:23.084+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250616T112445, start_date=20250616T112714, end_date=20250616T112823
[2025-06-16T11:28:23.237+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task stream_data_from_api (NoBrokersAvailable; 181)
[2025-06-16T11:28:23.351+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-06-16T11:28:23.504+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
