[2025-06-08T21:51:01.630+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T21:50:55.598399+00:00 [queued]>
[2025-06-08T21:51:01.692+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T21:50:55.598399+00:00 [queued]>
[2025-06-08T21:51:01.694+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-08T21:51:01.776+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-08 21:50:55.598399+00:00
[2025-06-08T21:51:01.795+0000] {standard_task_runner.py:57} INFO - Started process 276 to run task
[2025-06-08T21:51:01.802+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-08T21:50:55.598399+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpn9eg2_5b']
[2025-06-08T21:51:01.809+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-06-08T21:52:32.818+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T21:50:55.598399+00:00 [running]> on host 1caf33142b95
[2025-06-08T21:52:34.196+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T21:50:55.598399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T21:50:55.598399+00:00'
[2025-06-08T21:52:34.198+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 40, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2025-06-08T21:52:34.207+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250608T215055, start_date=20250608T215101, end_date=20250608T215234
[2025-06-08T21:52:34.216+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task stream_data_from_api (No module named 'kafka'; 276)
[2025-06-08T21:52:34.257+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-06-08T21:52:34.288+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
