[2025-06-14T14:41:03.149+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-13T00:00:00+00:00 [queued]>
[2025-06-14T14:41:03.159+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-13T00:00:00+00:00 [queued]>
[2025-06-14T14:41:03.160+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-14T14:41:03.169+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-13 00:00:00+00:00
[2025-06-14T14:41:03.181+0000] {standard_task_runner.py:57} INFO - Started process 257 to run task
[2025-06-14T14:41:03.184+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-06-13T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp4romf5o0']
[2025-06-14T14:41:03.187+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-06-14T14:41:03.274+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-13T00:00:00+00:00 [running]> on host af4e7496697c
[2025-06-14T14:41:04.509+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T00:00:00+00:00'
[2025-06-14T14:41:04.700+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-14T14:41:04.700+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-14T14:41:04.700+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-14T14:41:04.700+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-14T14:41:04.759+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-14T14:41:04.759+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-14T14:41:04.759+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-14T14:41:04.759+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-06-14T14:41:04.848+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-14T14:41:04.849+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-14T14:41:04.849+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-14T14:41:04.849+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.24 secs
[2025-06-14T14:41:05.092+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-14T14:41:05.093+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-14T14:41:05.093+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-14T14:41:05.093+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.35 secs
[2025-06-14T14:41:05.451+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-14T14:41:05.452+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-14T14:41:05.453+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-14T14:41:05.454+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.87 secs
[2025-06-14T14:41:06.330+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-14T14:41:06.331+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-14T14:41:06.332+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-14T14:41:06.335+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.36 secs
[2025-06-14T14:41:06.707+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 44, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms = 5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-06-14T14:41:06.743+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250613T000000, start_date=20250614T144103, end_date=20250614T144106
[2025-06-14T14:41:06.768+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task stream_data_from_api (NoBrokersAvailable; 257)
[2025-06-14T14:41:06.824+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-06-14T14:41:06.860+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
