[2025-06-16T08:08:44.104+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-15T00:00:00+00:00 [queued]>
[2025-06-16T08:08:44.111+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-15T00:00:00+00:00 [queued]>
[2025-06-16T08:08:44.111+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-16T08:08:44.118+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-15 00:00:00+00:00
[2025-06-16T08:08:44.127+0000] {standard_task_runner.py:57} INFO - Started process 4623 to run task
[2025-06-16T08:08:44.131+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-06-15T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmppw28s2rv']
[2025-06-16T08:08:44.133+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask stream_data_from_api
[2025-06-16T08:08:44.197+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-15T00:00:00+00:00 [running]> on host eb273acb5998
[2025-06-16T08:08:44.753+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-15T00:00:00+00:00'
[2025-06-16T08:08:45.060+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-16T08:08:45.060+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-16T08:08:45.060+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-16T08:08:45.060+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-16T08:08:45.115+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-16T08:08:45.116+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-16T08:08:45.117+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-16T08:08:45.117+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-06-16T08:08:45.211+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-16T08:08:45.212+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-16T08:08:45.212+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-16T08:08:45.213+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.23 secs
[2025-06-16T08:08:45.445+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-16T08:08:45.446+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-16T08:08:45.446+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-16T08:08:45.447+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.32 secs
[2025-06-16T08:08:45.769+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-16T08:08:45.771+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-16T08:08:45.771+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-16T08:08:45.772+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.71 secs
[2025-06-16T08:08:46.489+0000] {conn.py:1516} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-06-16T08:08:46.490+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2025-06-16T08:08:46.490+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-06-16T08:08:46.491+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.57 secs
[2025-06-16T08:08:47.062+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 44, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms = 5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-06-16T08:08:47.081+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250615T000000, start_date=20250616T080844, end_date=20250616T080847
[2025-06-16T08:08:47.096+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task stream_data_from_api (NoBrokersAvailable; 4623)
[2025-06-16T08:08:47.139+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-06-16T08:08:47.179+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
