[2025-06-08T22:46:12.439+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T22:46:10.605981+00:00 [queued]>
[2025-06-08T22:46:12.447+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T22:46:10.605981+00:00 [queued]>
[2025-06-08T22:46:12.448+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-08T22:46:12.459+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-08 22:46:10.605981+00:00
[2025-06-08T22:46:12.467+0000] {standard_task_runner.py:57} INFO - Started process 215 to run task
[2025-06-08T22:46:12.477+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-08T22:46:10.605981+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmplu907yxj']
[2025-06-08T22:46:12.480+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask stream_data_from_api
[2025-06-08T22:46:12.535+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T22:46:10.605981+00:00 [running]> on host 537e30a201fe
[2025-06-08T22:46:12.895+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T22:46:10.605981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T22:46:10.605981+00:00'
[2025-06-08T22:46:13.003+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.4', 29092)]>: connecting to broker:29092 [('10.89.0.4', 29092) IPv4]
[2025-06-08T22:46:13.015+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('10.89.0.4', 29092)]>: Broker version identified as 2.6
[2025-06-08T22:46:13.016+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Connection complete.
[2025-06-08T22:46:13.518+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('10.89.0.4', 29092)]>: connecting to broker:29092 [('10.89.0.4', 29092) IPv4]
[2025-06-08T22:46:13.521+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Connection complete.
[2025-06-08T22:46:13.523+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Closing connection. 
[2025-06-08T22:46:34.391+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:35.917+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:37.427+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:38.852+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:39.862+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:40.942+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:43.395+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:44.889+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:46.981+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:49.293+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:50.458+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:52.356+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:53.464+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:54.901+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:56.418+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:57.799+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:46:58.925+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:00.916+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:02.448+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:04.444+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:05.928+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:07.389+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:08.424+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:09.900+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:11.458+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:13.408+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:47:13.412+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Closing connection. 
[2025-06-08T22:47:13.416+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-08T22:47:13.494+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250608T224610, start_date=20250608T224612, end_date=20250608T224713
[2025-06-08T22:47:13.539+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-08T22:47:13.557+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
